yaml_files/fetch_in_if.yaml
yaml_files/fetch_out_if.yaml
yaml_files/fetch_env.yaml
yaml_files/decode_in_if.yaml
yaml_files/decode_out_if.yaml
yaml_files/decode_env.yaml
yaml_files/execute_in_if.yaml
yaml_files/execute_out_if.yaml
yaml_files/execute_env.yaml
yaml_files/control_in_if.yaml
yaml_files/control_out_if.yaml
yaml_files/control_env.yaml
yaml_files/memaccess_in_if.yaml
yaml_files/memaccess_out_if.yaml
yaml_files/memaccess_env.yaml
yaml_files/write_back_in_if.yaml
yaml_files/write_back_out_if.yaml
yaml_files/write_back_env.yaml
yaml_files/instr_mem_if.yaml
yaml_files/data_mem_if.yaml
yaml_files/LC3_env.yaml
yaml_files/LC3_bench.yaml

